dataset_params:
  im_channels: 1
  im_size: 256
  name: 'adni'

diffusion_params:
  num_timesteps : 1000
  beta_start : 0.00085
  beta_end : 0.012

ldm_params:
  down_channels : [256, 384, 512, 768]
  mid_channels : [768, 512]
  down_sample : [True, True, True]
  attn_down: [True, True, True]
  time_emb_dim : 512
  norm_channels: 32
  num_heads : 16
  conv_out_channels: 128
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2
  condition_config:
    condition_types: ['context']
    context_condition_config:
      attention_levels: [False, True, True]
      context_embed_dim: 768

vae_params:
  z_channels: 4
  down_channels: [64, 128, 256, 256]
  mid_channels: [256, 256]
  down_sample: [True, True, True]
  attn_down: [False, False, False]
  norm_channels: 32
  num_heads: 4
  num_down_layers: 2
  num_mid_layers: 2
  num_up_layers: 2

train_params:
  seed: 1111
  task_name: 'adni'
  ldm_batch_size: 16
  vae_batch_size: 1
  disc_step_start: 15000
  disc_weight: 0.5
  perceptual_weight: 0.0
  kl_weight: 0.000005
  ldm_epochs: 100
  vae_epochs: 20
  num_samples : 1
  num_grid_rows : 1
  num_workers: 8
  ldm_lr: 0.000005
  vae_lr: 0.00001
  vae_acc_steps: 4
  vae_image_save_steps: 256
  save_latents: False
  vae_latent_dir_name: 'vae_latents'
  ldm_ckpt_name: 'ddpm_ckpt.pth'
  vae_autoencoder_ckpt_name: 'vae_autoencoder_ckpt.pth'
  vae_discriminator_ckpt_name: 'vae_discriminator_ckpt.pth'
  dataset_csv: '/home/chsong/project/longitudinal/utils/dataset.csv'
  cache_dir: '/DataRead2/chsong/cache'
